### ISSUE TITLE
Type to keep track of current full order book

### ISSUE THREAD

**Issue by gaillard** [preichenberger/go-gdax#30]
Would be great to see a type that could implement what's described https://docs.gdax.com/#the-code-classprettyprintfullcode-channel.
I might work on this when I get some time.

**Comment by preichenberger** [comment]
Does Message https://godoc.org/github.com/preichenberger/go-coinbase-exchange#Message not handle this?

**Comment by gaillard** [comment]
Yes Message can be used just like in the README to get the stream of messages just fine, but what I was suggesting was a type that maintains the state of the full order book.

**Comment by preichenberger** [comment]
Gonna close this for now. If more people request this feature we can revisit
