### ISSUE TITLE
Sending float64s via JSON to GDAX results in "Price too precise" errors

### ISSUE THREAD

**Issue by cgarvie** [preichenberger/go-gdax#37]
Currently, use of this library to CreateOrder()s often fails, because the price must be sent as a float64 to the library (as opposed to a string), and is then converted to a string with too much precision. The GDAX API then rejects these orders with an error message, explaining that the "price [is] too precise."

More generally, the use of float64s is probably not ideal.

**Comment by ColtonProvias** [comment]
It may be good for a fork of this to switch from float64 to Shopspring's Decimal library: https://github.com/shopspring/decimal

**Comment by tmc** [comment]
refs https://github.com/preichenberger/go-gdax/issues/18

**Comment by preichenberger** [comment]
@ivy suggested we use strings and have the user bring their own decimal lib. I did an initial pass in this pr: https://github.com/preichenberger/go-gdax/pull/48

I chose not to add shopspring's decimal. It will still require the user to call decimal directly when they "use" a price, so it will only save one convert at the expense of adding a 3rd party dependency.

Feedback is welcome!

**Comment by chrischris292** [comment]
any updates here? This is a pretty serious issue.

**Comment by preichenberger** [comment]
Closed with https://github.com/preichenberger/go-gdax/pull/48
