### ISSUE TITLE
Level2 not working

### ISSUE THREAD

**Issue by watershine** [preichenberger/go-gdax#41]
I'm not sure if I'm missing something but I can't make websocket work for level2. The returned structure is different than the Message one and I can't find the right one in the project. Any help would be appreciated.

**Comment by preichenberger** [comment]
I added a way to specify channels on websocket subscribe, its in the README as well. https://github.com/preichenberger/go-gdax/commit/77508b321c9785d9d8d804d564794d5bf6d4283e

You can use access information doing: message.Bids, message.Asks, message.Changes
