### ISSUE TITLE
Orderbook? 

### ISSUE THREAD

**Issue by chrischris292** [preichenberger/go-gdax#42]
It'd be nice to have orderbook code here....support for L3 would also be nice.

**Comment by lego** [comment]
There is support for an order book! Check out the [godocs](https://godoc.org/github.com/preichenberger/go-gdax#Client.GetBook) and the [source](https://github.com/preichenberger/go-gdax/blob/master/product.go#L178-L184).

**Comment by chrischris292** [comment]
Sorry, to be more specific, an orderbook with websocket integration.

**Comment by chrcoe** [comment]
can't you use the websocket level2 channel to get your order book?

you would end up with a [Message](https://godoc.org/github.com/preichenberger/go-gdax#Message) from the websocket, which you then can utilize in your app.

**Comment by chrischris292** [comment]
Yes that is correct but an orderbook type is what I’m looking for. https://github.com/danpaquin/gdax-python/blob/master/gdax/order_book.py

**Comment by chrcoe** [comment]
ah ok, yea right now this library has the ability to utilize websockets but not really a websocket client.

@preichenberger is that something you would see wanting in your library? (a WebsocketClient)

**Comment by chrischris292** [comment]
Yeah, a Websocketclient would be nice. An orderbook class which exists separately from the websocketclient would also be nice. An orderbook is useful for many analytical application and many trading strategies may be interested in analyzing this.

**Comment by chrcoe** [comment]
i would envision a WebsocketClient which acts similar to the regular Client.  It would then theoretically be able to have a GetBook() function which returns a Book (this is the order book).

something like this:
`func (c *WebsocketClient) GetBook(product string, level int) (Book, error)`

where [Book](https://godoc.org/github.com/preichenberger/go-gdax#Book) is still the same struct

**Comment by chrischris292** [comment]
ah sorry my bad i overlooked that. thanks
