### ISSUE TITLE
orderbook: get highest bid and lowest ask

### ISSUE THREAD

**Issue by mbana** [preichenberger/go-gdax#55]
Note: the `ticker` channel on the websocket feed does not return the highest bid and lowest ask.

It would be nice to get the highest bid and lowest ask price from the websocket feed and expose this to the user somehow.

I have some working code to keep in sync with the highest bid. It requires listening to certain messages and maintaining an orderbook with only one level - the top bid. The messages to listen to are `snapshot` and `l2update`.

Does anyone know of an easier way to always get the highest bid and lowest ask without polling the HTTP endpoint?

**Comment by forward32** [comment]
@mbana There is no easier way. Listening Websocket L2 channel is your best choice in that case.

**Comment by mbana** [comment]
I've managed to do it for the highest bid by subscribing to the `level2` channel. it seems to be working fine. Doing the same for the lowest ask shouldn't be to hard.

What I am pushing for wanting to know is, will this make it into the core? 'cause that's what I'd like as more people will get to look at it and spot any errors. Effectively provide an orderbook in this library.

Another approach which I've managed to get to work as well is using the [gdax-tt](https://github.com/coinbase/gdax-tt/), which provides both the highest bid and lowest ask, and sending the price updates on a channel using RabbitMQ then listen to this channel in Go. Of course this isn't a great solution but it works.

**Comment by forward32** [comment]
I'm not owner of this repo so I don't know about future plans, but I guess you feel free to implement it and create pull request.

**Comment by mbana** [comment]
I will create a PR at some point that addresses this issue.

Thanks for the feedback.

**Comment by mbana** [comment]
You can follow this branch which contains the WebSocket code to maintain a level2 orderbook:

https://github.com/banaio/go-gdax/tree/track_highest_bid

I will raise a PR so that I can get some initial feedback.

**Comment by preichenberger** [comment]
From an organization standpoint, I think this library should just be an API client while another library should be for higher level trading needs (similar to gdax-tt) I see you've done a lot of work, I think it would make sense to create a new repo and then use gdax-go as a dependency.

Thoughts?

**Comment by mbana** [comment]
There are some changes that should be part of the core I think, e.g., parsing in the `Message` that is received by the socket: https://github.com/preichenberger/go-gdax/pull/59/files#diff-b95c50d14ed7b4bb1cfecdc4e498d4dc

`gdax-tt`  provides a socket connection and a level2 book, they might even support a level3 one I am not quiet sure.

Can you list your concerns more concretely, as I feel like I am missing the point.

**Comment by chrischris292** [comment]
+1

**Comment by preichenberger** [comment]
I think this library should only do the following
  - Authentication
  - Preparing and making gdax requests
  - Models for serializing/deserializing

I've added your changes regarding snapshot entries/changes: https://github.com/preichenberger/go-gdax/commit/ed4008f50f53ec70419ee58220205c362eb2e287 I think this fits under "Creating models..."

The order book management logic is more higher level and more concerned with trading tools (similar to gdax-tt) rather than simply getting data from the API.

**Comment by preichenberger** [comment]
Closing for now.
