### ISSUE TITLE
Websocket signing appears to be incorrect

### ISSUE THREAD

**Issue by fbatogo** [preichenberger/go-gdax#56]
According to the GDAX documentation at : https://docs.gdax.com/#signing-a-message a message signature needs to be created using a timestamp, method, requestPath, and body.   However, the Sign() method in signing.go appears to only use the timestamp, method, and requestPath.

Interestingly enough, the code that doesn't use the websocket actually appears to use all 4 of the components.

Another interesting tidbit about this is the current signing implementation appears to work just fine on the GDAX sandbox.   But, on the real GDAX site, it seems to have issues.   When I use it to send a subscription message that includes the user channel, I then get a subscription response that claims I am subscribed to the user channel.   However, creating an order doesn't result in any order messages coming in, and an order being matched also doesn't result in any messages on the user channel.   Since the sandbox generates user messages for these actions, I suspect that GDAX has a bug in how they are handling the subscription messages.   They seem to always tell you that you are subscribed to whatever channels you request.   However, if the signature is invalid they just don't appear to send messages.   I've sent an e-mail to GDAX support about this, but suspect I won't get an answer from them. :-(

I'll be forking the project to attempt to fix the issue, and will submit a pull request if I get anywhere with it.  But, I figured I would open a bug report in case someone else gets to the issue first, or in case someone else is fighting with the user channel not working.

**Comment by preichenberger** [comment]
I'm not sure what the body would be for websocket signing. In the GDAX node library (I believe it's maintained by Coinbase themselves), no body is supplied: https://github.com/coinbase/gdax-node/blob/master/lib/clients/websocket.js#L64

**Comment by fbatogo** [comment]
You are correct.  With a bit more debugging I verified the implementation is correct.  Sorry for the bother.
