### ISSUE TITLE
Multiple fields in Message may be broken

### ISSUE THREAD

**Issue by zhengyangfeng00** [preichenberger/go-gdax#60]
For example, in previous versions, the Bids field of the Message is defined as following [link](https://github.com/preichenberger/go-gdax/blob/14875e94b343f1528d1f101ceebc5885a6e3d19d/message.go#L25):
``` go
Bids [][]string `json:"bids,omitempty"`
```

In the latest version, it is defined as [link](https://github.com/preichenberger/go-gdax/blob/ed4008f50f53ec70419ee58220205c362eb2e287/message.go#L29):
``` go
Bids [][]SnapshotEntry `json:"bids,omitempty"`
```

where `SnapshotEntry` is a tuple of 3 values. Essentially it makes Bids field match `[][][]string` and it will obviously failed to unmarshal the json message. Is this a bug or I misunderstood the intention?

**Comment by preichenberger** [comment]
Thanks for catching this. It was just added recently. Should be fixed in: https://github.com/preichenberger/go-gdax/commit/b9e9c04fb8b4614f02af36fd4eabe81a36bc0eda
