### ISSUE TITLE
GetHistoricRate doesn't work

### ISSUE THREAD

**Issue by chrischris292** [preichenberger/go-gdax#61]
Returns "Expected string" error. Fails when trying to parse the time in the array

**Comment by chrischris292** [comment]
It's because of the last PR for https://github.com/preichenberger/go-gdax/pull/48. Golang doesn't like the conversion to string...expects float64....

**Comment by preichenberger** [comment]
Fixed in: https://github.com/preichenberger/go-gdax/commit/9f655a0fe4900955cb03da9c37f186b463cb9339

Re-enabled GetHistoricRates test as well
