### ISSUE TITLE
GetHistoricRates parameters

### ISSUE THREAD

**Issue by schm03** [preichenberger/go-gdax#71]
I'm new to GoLang, which may be the problem, but I cannot figure out how to pass start, end and granularity to the GetHistoricRates function.

I've even tried passing a struct of type GetHistoricRatesParams with no success.

Note, I *am able to retrieve a default history by simply passing the Product ID.

**Comment by preichenberger** [comment]
Hi, you can see here the signature for the GetHistoricRates method:
https://godoc.org/github.com/preichenberger/go-gdax#Client.GetHistoricRates

Here is the GetHistoricRatesparams that the signature references:
https://godoc.org/github.com/preichenberger/go-gdax#GetHistoricRatesParams

Example:
`
now := time.Now()
getHistoricRatesParams := gdax.GetHistoricRatesParams{
  Start: now.Sub(1 * time.Hour),
  End: now,
  Granularity: 60,
}
rates, err := client.GetHistoricRates("BTC_USD", getHistoricRatesParams)
`
