### ISSUE TITLE
Cannot unmarshal number into Go struct field of Ticker.volume

### ISSUE THREAD

**Issue by fbatogo** [preichenberger/go-gdax#72]
Let me start by saying that I know that this is ultimately an issue with the GDAX/Coinbase API, but I figured I would open a bug here as well in case there is a workaround that could be put in place.

When calling GetTicker() with the symbols :  

ETH-BTC
LTC-EUR
BCH-BTC
BTC-GBP
ETC-USD
ETC-EUR
ETC-BTC

They all error out an return the message "Cannot unmarshal number into Go struct field of Ticker.volume".   I suspect that for those tickers the volume is geting returned as either an int or a float, but have not had time to dig in to see yet.  (To be fair, the docs at https://docs.pro.coinbase.com/#get-product-ticker don't actually SAY that volume will be a string, but it sure seems to imply it!)

I will also attempt to locate a way to submit this information to GDAX/Coinbase to attempt to get them to fix the issue.

**Comment by preichenberger** [comment]
Looks like at first glance it returns an int if the value is zero. I've added a new type to handle if it returns a string or an it (though I wish they would be more consistent with their types)

https://github.com/preichenberger/go-gdax/commit/86d7e6cd55f98ec5cae520a90c5ed27f44d51402
